---
# time-related tasks

- name: install system packages for time management
  apt: pkg=ntp,tzdata state=latest update-cache=yes cache_valid_time=3600

- name: set timezone to {{ timezone }}
  template: src=etc/timezone dest=/etc/timezone
  notify: update-tzdata

- name: Set default system language pack
  shell: locale-gen {{locale}}
  sudo: yes

- name: set local to {{ locale }}
  template: src=etc/environment dest=/etc/environment
  notify: update-tzdata
  sudo: yes