---
- name: Webserver for Symfony app
  hosts: all
  vars_files:
    - vars/main.yml
  sudo: yes
  gather_facts: true
  roles:
    - common        # Common packages
    - JasonGiedymin.nodejs
    - nginx-symfony
    - Ansibles.mysql # Database
    - php

